{
 "title": "Cell Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current 5G Band",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomo_5g_band", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current 5G CellID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomo_5g_cell_id", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data This Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomo_cell_bytes_sent", "legendFormat": "Sent" },
    { "expr": "gomo_cell_bytes_received", "legendFormat": "Received" }
   ]
  },
  {
   "title": "Current LTE Band",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomo_lte_band", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current LTE CellID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gomo_lte_cell_id", "legendFormat": "__auto" }
   ]
  },
  { "title": "5G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "5G SNR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "gomo_5g_snr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5G RSRP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "gomo_5g_rsrp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5G RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "gomo_5g_rsrq", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5G Band",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "targets": [
    { "expr": "gomo_5g_band", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5G CellID",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "targets": [
    { "expr": "gomo_5g_cell_id", "legendFormat": "__auto" }
   ]
  },
  { "title": "LTE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "LTE SNR",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "gomo_lte_snr", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LTE RSRP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "gomo_lte_rsrp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LTE RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "gomo_lte_rsrq", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LTE Band",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "targets": [
    { "expr": "gomo_lte_band", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LTE CellID",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "targets": [
    { "expr": "gomo_lte_cell_id", "legendFormat": "__auto" }
   ]
  }
 ]
}