global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'gomo'
    scrape_interval: 3s
    scrape_timeout:  3s
    static_configs:
      - targets: ['host.docker.internal:2112']